version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - main
    depends_on:
      - db 

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/    
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_DB: festivitiesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    command: -p 5434  
    networks:
      - main      
    
volumes:
  postgres_data:

networks:
  main:
    driver: bridge