# Generated by Django 3.1.6 on 2021-02-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivity',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='festivity',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
